server: 
  port: 8081                    
#  address: 0.0.0.0
#  servlet:
#    context-path: /product-server
    
spring:
  application:
    name: product-server
    
  datasource:
    url: jdbc:mysql://127.0.0.1:4406/product_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 
    # 8.x版本的MySQL JDBC驱动类为com.mysql.cj.jdbc.Driver
    # 5.X版本的MySQL JDBC驱动类为com.mysql.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000    
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000  
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000  
      test-while-idle: true
      test-on-borrow:  false
      test-on-return: false
      ## 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter: stat, wall, log4j
      use-global-data-source-stat:   true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 合并多个DruidDataSource的监控数据
      #spring.datasource.useGlobalDataSourceStat=true
      # druid 监控配置
      #StatViewServlet配置，说明请参考Druid Wiki，
      
# mybatis 基本配置
mybatis:
  # 配置Java类型包名
  type-aliases-package: com.gerry.pang.product.entity
  # 注册XML映射器
  mapper-locations: classpath:mapper/**/*.xml,classpath*:/com/gerry/pang/**/**mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 
    default-fetch-size: 20
    default-statement-timeout: 30       
  # 是否检测MyBatis运行参数配置文件
  check-config-location: true 
  # 指定MyBatis运行参数配置文件位置                            
  # config-location: classpath:/mybatis-config.xml
  # 配置类型处理器包名          
  type-handlers-package: com.gerry.pang.product.handlers
  # 指定执行器类型         
  executor-type: SIMPLE                                   

# feign配置
feign:
  client:
    config:
      default:
        # 连接超时
        connectTimeout: 5000
        # 读取超时
        readTimeout: 5000
        # 日志等级
        loggerLevel: basic
  httpclient:
    enabled: true      
  okhttp:
    enabled: false
  hystrix:
    enabled: false
  # 压缩
  compression:
    # 请求
    request:
      # 是否开启
      enabled: true
      # 配置压缩数据大小的下限
      min-request-size: 2048
      # 开启支持压缩的MIME TYPE
      mime-types:
      - application/json
      - application/xml
      - text/xml
    # 响应
    response:
      enabled: true
      useGzipDecoder: true

      
      
      