// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloWorld.proto

package com.gerry.pang.grpc.api;

public final class HelloWorldProto {
  private HelloWorldProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020HelloWorld.proto\022\nhelloworld\"`\n\014HelloR" +
      "equest\022\023\n\013serviceName\030\001 \001(\t\022\022\n\nmethodNam" +
      "e\030\002 \001(\t\022\023\n\013messageData\030\003 \001(\t\022\022\n\nrequest_" +
      "id\030\004 \001(\t\"a\n\rHelloResponse\022\023\n\013serviceName" +
      "\030\001 \001(\t\022\022\n\nmethodName\030\002 \001(\t\022\023\n\013messageDat" +
      "a\030\003 \001(\t\022\022\n\nrequest_id\030\004 \001(\t2U\n\014HelloServ" +
      "ice\022E\n\010SayHello\022\030.helloworld.HelloReques" +
      "t\032\031.helloworld.HelloResponse\"\000(\0010\001BJ\n\027co" +
      "m.gerry.pang.grpc.apiB\017HelloWorldProtoP\001" +
      "Z\026pbfs/double_way_stream\242\002\003HLWb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_helloworld_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helloworld_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_HelloRequest_descriptor,
        new java.lang.String[] { "ServiceName", "MethodName", "MessageData", "RequestId", });
    internal_static_helloworld_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_helloworld_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_HelloResponse_descriptor,
        new java.lang.String[] { "ServiceName", "MethodName", "MessageData", "RequestId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
